# Generated by Django 5.1.5 on 2025-03-20 09:15

import assistant.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_classwork_deadline_alter_classwork_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload your work file (PDF, DOCX, PNG, etc.).', upload_to=assistant.models.student_submission_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('classwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assistant.classwork')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_works', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
