# Generated by Django 5.1.5 on 2025-05-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
