# Generated by Django 5.1.5 on 2025-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_testimonial_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwork',
            name='category',
            field=models.CharField(choices=[('notes', 'Notes'), ('test', 'Test'), ('assignment', 'Assignment')], default='notes', max_length=20),
        ),
    ]
