# Generated by Django 5.1.5 on 2025-09-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_classwork_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classwork',
            name='category',
            field=models.CharField(choices=[('notes', 'Notes'), ('test', 'Test'), ('assignment', 'Assignment')], max_length=20),
        ),
    ]
