# Generated by Django 5.1.5 on 2025-09-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_customuser_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentwork',
            name='ai_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentwork',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentwork',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentwork',
            name='plagiarism_matches',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentwork',
            name='plagiarism_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
