# Generated by Django 5.1.5 on 2025-09-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0011_studentwork_ai_feedback_studentwork_ai_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwork',
            name='ai_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
